baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Bột Cần Tây Yume'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Product of Moc Van Thanh Jsc'

seo:
  meta_og_title: "Bot Can Tay"
  meta_og_type: "website"
  meta_og_url: "https://botcantayvietnam.com"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Bột cần tây Yume được sản xuất từ 100% Cần Tây đạt tiêu chuẩn VietGap, thu hái và sấy luôn trong ngày bằng công nghệ sấy lạnh của Nhật Bản."
  meta_twitter_card: "summary"
  meta_twitter_site: "@thanqminh"
  meta_twitter_creator: "@thanqminh"

collections:
  products:
    output: true
  dealers:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
